### ISSUE TITLE
RecipeManager prevents combining tools/weapons/armour in crafting square (2x2) and workbench

### ISSUE THREAD

**Issue by totemo** [haveric/RecipeManager2#110]
I'm really hoping this is a simple one. I've searched through the issues and the RecipeManager configs and can't find it.

In the default configuration, RecipeManager prevents players from combining two items on the workbench or inventory 2x2 crafting square, e.g. two slightly damaged bows. The plugin does play the custom, sped-up anvil sound, but no item appears in the crafting output slot.

Apparently this has been going on since 1.18 or maybe earlier. We're currently running RecipeManager 2.29.1 on Spigot and PaperSpigot for 1.18.1 and 1.19.2. I have tested multiple server versions and it seems to be down to RecipeManager. Disabling the plugin restores vanilla behaviour.

**Comment by haveric** [comment]
This should already be fixed in v2.29.2, which is pending review on dev.bukkit.org, but is available in the github releases: https://github.com/haveric/RecipeManager2/releases

Please let me know if that does not fix your issue.

**Comment by totemo** [comment]
I did see the 2.29.2 release but since it didn't say anything about that bug I didn't rush to test it.

I have now tested it on 1.19.2 with the default RecipeManager configuration and the result is the same: *clink* *clink* *clink* but no output item.

**Comment by totemo** [comment]
Hi, I don't mean to be a nuisance, and I understand if you don't have time to devote to this right now, but this problem still exists in 2.29.2.

**Comment by haveric** [comment]
Apologies for the delay. The latest devbuilds (v2.29.2-dev2 being the most recent) on [discord](https://discord.gg/3JY9JC3) include a fix for this. A proper release will coming soon*

\* (hopefully in the next couple weeks, but depends if any other issues pop up in that time)

**Comment by totemo** [comment]
Thanks for that! I just tested a build and combining items in the crafting square is working again.

**Comment by haveric** [comment]
This should now be fixed as of v2.30.0. If you're still running into issues, please create a new issue with any updated details.
