### ISSUE TITLE
Brewing recipe not working

### ISSUE THREAD

**Issue by mc-yuu2132** [haveric/RecipeManager2#113]
The recipe using the brewing table does not seem to work. We added the recipe as described in the "Basic Recipes.html" file that came with the plugin and checked that there were no errors, but the recipe did not work.
We tried typing "/itemname &cTest" using CMI for the item and also using the anvil to type "&cTest", neither of which seemed to work.
We are currently running 1.19.3 paperspigot and v2.29.2 recipe manager
We look forward to the day when it will be corrected!
P.S.
Is it possible to add diamonds as an ingredient to a brewing recipe? 
Do we need to list an additional recipe as well as a 'fuel' to be able to add them?

[Code we used when adding recipes]

brew
a nether_wart
@name &cTest
b potion
@potion type water
= stone
@name <red>Test Stone. Please Ignore

**Comment by haveric** [comment]
I suspect that the methods you are using do not create the same item meta that it's looking for. Usually, this has to do with the color code not matching the same way.

Using the following recipe as a test case, the resulting nether wart works correctly in the brewing recipe:

````
craft
nether_wart + nether_wart
= nether_wart
@name &cTest
````

If this still doesn't work for you or you need this to work with one of your other methods of creating items, you should be able to investigate the meta of the selected item with `/data get entity @s SelectedItem.tag` to try to figure out what is different in the other methods of creating/modifying items and if you need help making those work with the brewing recipe, please let me know and I'll try to help.

**Comment by mc-yuu2132** [comment]
Thank you for responding!
We tried the method you quickly taught us, but it did not work.
We don't think this problem is caused by nbt differences, as the same method worked for other recipes (e.g. crafting).
To test this, we did not set a colour code for the generated items and the items needed for the brewing recipe.
[Create Material Items]
craft
nether_wart + nether_wart
= nether_wart
@name Test.

[Create brewing recipe]
brew
a nether_wart
@name Test
b potion
Potion type water
= stone
@name Test Stone. Please ignore

The above method did not produce a named stone. The brewing table produces "awkward potion".
We are very sorry, but if your brewing recipe is possible with the above method, please contact us again.
Perhaps another plugin is doing something wrong.

**Comment by haveric** [comment]
There are two formatting issues with your recipes:
- In the first recipe, you are creating an item with the name "Test.", which includes a period, and the brewing recipe is looking for "Test" without a period. If you're using flags within the ingredients, all metadata needs to match exactly or the recipes will not work.
- In the brewing recipe, you need to include an `@` before "potion type water"

The recipe is working for me with exactly these:
```
craft
nether_wart + nether_wart
= nether_wart
@name Test.

brew
a nether_wart
@name Test.
b potion
@Potion type water
= stone
@name Test Stone. Please ignore
```

If that still doesn't work, there might be a permission issue going on. Please run /rmdebug when looking at the brewing stand and send me the output. While unlikely, it's also possible the state is messed up and picking up and replacing the brewing stand will reset things to a working state.

**Comment by mc-yuu2132** [comment]
Sorry for the repetition.
We ran it again with the conditions below, but it did not build.
We ran /rmdebug and also checked the permissions on the brewer's table, so we're attaching a photo!

CRAFT
nether_wart + nether_wart
= nether_wart
@name Test

brew
a nether_wart
@name Test
b potion
@Potion type water
= stone
@name Test Stone. Please Ignore

<img width="408" alt="image" src="https://user-images.githubusercontent.com/113339718/220082091-4fb78794-df35-424d-94a6-d758af0e74c3.png">

**Comment by mc-yuu2132** [comment]
We have now experimented again and were actually able to create a stone when the data on the brewing table was zero (the @name did not seem to work...)!
When we created it again, data was added and the recipe stopped working again.
This seems to be the reason why the recipe was not working correctly.
<img width="288" alt="image" src="https://user-images.githubusercontent.com/113339718/220085824-0b766fe4-7ac1-4b33-b961-e024dc211f59.png">

<img width="323" alt="image" src="https://user-images.githubusercontent.com/113339718/220085659-071dd60b-4b50-4cf3-984b-7cd52673f800.png">

**Comment by haveric** [comment]
I think I've narrowed down the issue a bit, but still need to do some more testing to figure out why it's happening and how to fix it.

If you're using an ingredient that is already used in brewing recipes (such as nether wart), placing the potions first and the nether wart last works, but the reverse will not work, which is of course how brewing stands are usually used. Using a new material (such as dirt) works with either order though, so if you're willing to use new materials for now, it should get around this issue until I am able to fix it.

**Comment by mc-yuu2132** [comment]
Thanks for fixing it!
We used the dev version that was released as soon as possible. We were able to create a brewing recipe without any problems :D
It seems that when you set the 'name', 'lore', 'custommodeldata' etc, you have to list them all after the ingredients. That gave us a little headache.

**Comment by mc-yuu2132** [comment]
Once the brew recipe has been written and loaded into the Recipes txt file, no more brew ingredients can be delivered to the brew table via the hopper.
(this includes ingredients that can be used by default)

**Comment by haveric** [comment]
Hopper functionality shouldn't be affected by these changes. Can you include any brewing recipes you have defined as well as screenshot your hopper/brewing stand setups?

**Comment by mc-yuu2132** [comment]
OK, I upload the recipe I set up and a picture of the hopper and brew table I set up.
If I delete only the brew recipe and run /rmreload, the contents of the hopper are loaded into the brew table, if I add the brew recipe again and run /rmreload, the hopper is not loaded into the brew table.
It works perfectly except for a problem with material not being discharged from the hopper.

[Recipe]
brew
a GUNPOWDER
b POTION
=POTION

Photo.
(How the hopper and brewing table were placed and their contents)
<img width="213" alt="image" src="https://user-images.githubusercontent.com/113339718/224465656-a72422ab-6b67-4345-8f9e-a0b7afb753e9.png">
<img width="191" alt="image" src="https://user-images.githubusercontent.com/113339718/224465646-f87ba67a-fa3e-4e52-ae2c-520ef7ea2aab.png">
<img width="174" alt="image" src="https://user-images.githubusercontent.com/113339718/224465635-8683b8a5-2292-4973-8d84-977a8675b41a.png">

**Comment by mc-yuu2132** [comment]
I don't know why, but I've just tried again with the same equipment and it worked.
Sorry, I'll let you know if I get the same situation again...

**Comment by haveric** [comment]
That's certainly strange. Please let me know if you get it to happen again, so we can narrow down how it's happening.

**Comment by mc-yuu2132** [comment]
So far this problem has not recurred.
If it happens again, I will contact you. Thank you for your support:D
