### ISSUE TITLE
@potionitem custom does not support color

### ISSUE THREAD

**Issue by mc-yuu2132** [haveric/RecipeManager2#114]
I'm currently running 1.19.3 paper/spigot and v2.29.2-dev1 recipe manager
When set to [@potionitem type INVISIBILITY | color 255 128 0], color works correctly.
However, when set to [@potionitem custom INVISIBILITY | duration 1800 | color 255 128 0], it throws an error and cannot be executed.
Paste the error message into the console.

[01:02:42 INFO]: [RecipeManager] File: Brewing Custom.txt
line 26   Warning: Flag @potionitem has unknown argument: color 255 128 0
          TIP: Maybe it's spelled wrong, check it in 'recipe flags.html' file.

I have read the html. It does not seem to be written incorrectly.
Please help meXd

**Comment by haveric** [comment]
The documentation may not be the clearest on this, but color can only be defined on the basic potion. Custom effects should be added after.

In your case, you should be able to use both lines together to create the effect you want:
```
@potionitem type INVISIBILITY | color 255 128 0
@potionitem custom INVISIBILITY | duration 1800
```

**Comment by mc-yuu2132** [comment]
Oh, I see! So that's what you did!
In this case, it was annoying to see two different times, so I used @hide and listed the new effect and time in the lore.
The @ingredientcondition can be applied to materials, but can't it be applied to potions? That would open up so many possibilities!

**Comment by haveric** [comment]
> In this case, it was annoying to see two different times, so I used @hide and listed the new effect and time in the lore.

Ah, that makes sense. I suspect if you change the initial [potion type](https://www.recipemanager.dev/docs/latest/name%20index.html#potiontype) to one that doesn't show anything, you might not run into this issue, but if you've got it working, that's all that matters.

> The @ingredientcondition can be applied to materials, but can't it be applied to potions?

Yes, it handles potion and potioneffect. See the [documentation](https://www.recipemanager.dev/docs/latest/recipe%20flags.html#ingredientcondition) for more details on how to use it.
