### ISSUE TITLE
Smelting recipes don't fully support ingredientcondition

### ISSUE THREAD

**Issue by haveric** [haveric/RecipeManager2#27]
Example from adw123:

I found a bug with smelting recipes. They don't seem to work at least with some ingredient conditions. See config below.

smelt Bronze Ingot Recipe

coal_block
= iron_ingot
@name Bronze Ingot
@lore <gray>
@lore This is a Tier 2 Crafting Component.
@ingredientcondition coal_block | name Bronze Cluster
@permission ils.use.agent

Right now this recipe will work with a regular coal block whether its named "Bronze Cluster" or not. Seems to work this way for iron, gold, and diamond blocks as well.

**Comment by haveric** [comment]
The last commit sorta fixed this, but instead of not smelting with an invalid item, it will smelt and the item will disappear. I'm pretty sure I know why, but I'll have to look at it another day.

**Comment by SoSeDiK** [comment]
Is there any progress on this problem? By the way, this is somehow possible in ProRecipes.

**Comment by haveric** [comment]
Unfortunately, this will require a full rewrite of how furnace recipes are working currently to get around the limitations of what Minecraft and Bukkit/Spigot allow normally. This would take a lot of time and effort to get right, but I hope it can happen eventually. No, there is no timeline on this because it is a giant undertaking that may not even work in the end.

Taking a look at the ProRecipes source, I'm not seeing anything that handles even close to the complexity that RecipeManager does for conditions so that codebase would not be much help in solving the issue for RecipeManager.

If you have a specific example of what you're trying to do, perhaps I could help you more as there is still quite a bit of functionality working even for furnaces, but please create a new issue for that so that there can be more discussion specific to what you're creating.
