### ISSUE TITLE
@restrict causing a warning

### ISSUE THREAD

**Issue by SonarBeserk** [haveric/RecipeManager2#39]
@restrict causes a warning when using it is used for minecraft made recipes. 

When the definition is: 
"    Restricts the recipe to everybody.
    This is the player-friendly version of @remove because crafter gets a message when trying to craft the recipe."

I wouldn't expect a warning to result.

**Comment by haveric** [comment]
What is the recipe used and the warning you get?

**Comment by SonarBeserk** [comment]
@restrict <red>This item is banned for balancing reasons!
diamond:0 + air + diamond:0
diamond:0 + diamond:0 + diamond:0
Recipe:

diamond:0 + diamond:0 + diamond:0
= diamond_chestplate:0:1
Warning:

File: diamondban
line 1    Warning: Recipe already created by Minecraft, recipe overwritten!
          TIP: You can use @override flag to overwrite the recipe or @remove to just remove it.

**Comment by haveric** [comment]
The quick solution is to set "disable-override-warnings" to true in config.yml. There's quite a bit of code that needs to be updated to improve things like this, but they may take some time.

**Comment by SonarBeserk** [comment]
Alright, want me to leave the ticket open in the meantime?

**Comment by haveric** [comment]
That's fine, it'll be a reminder for me to look into it a bit more.
