### ISSUE TITLE
adding items via Shift-click to furnace allows stacking and dublicating enchantments

### ISSUE THREAD

**Issue by Bastikeks** [haveric/RecipeManager2#40]
when shiftclicking ANY item in the inventory inside a furnace gui, the item getw placed in the configured slot like defined in config.yml. BUT this also works when there is still an item in the slot and so non-stackable items like swords can be stacked. By that you can stack e.g. normal Diamond pickaxes and then finally add an enchanted pickaxe to get a whole stack of these.
Is there any permission to deny this or is this a bug? If so I hope this will get fixed soon :)

**Comment by haveric** [comment]
Please test this on v2.4 and let me know if it is still happening.
