### ISSUE TITLE
BUG on furnace

### ISSUE THREAD

**Issue by Yooly** [haveric/RecipeManager2#45]
First, please forgive my poor English, the following are from the Google translation.
If you don't understand, I really don't know how to do the.

BUG operational processes is:
Use stealth button all the material(not fuel) into the furnace, the result are not supported @name & @lore, But the default name items. If you use the mouse to drag and drop into it, it is supported.

My server info:
PaperSpigot-1.8.8
Plugins (8): PermissionsEx, WorldEdit, Vault, Essentials, OtherDrops, EssentialsSpawn, ASkyBlock, RecipeManager

thinks.

**Comment by haveric** [comment]
Can you provide the recipes you are using? Please use http://pastebin.com/ if you have a lot.

Does the same thing happen when running only RecipeManager?

I'm assuming "Use stealth button" was translated incorrectly and should be "shift click". Please let me know if that is incorrect.

**Comment by Yooly** [comment]
It's "shift click",
This is my recipes

smelt SLIME_BALL
18:0
= 341
@name <white>Glue
@lore <gray>It looks like the slime ball.

Thinks.

**Comment by ahoyaharr** [comment]
Reporting that I am experiencing a similar issue with all furnace recipes. The only parameter which seems unaffected is the chance modifier. In the following recipe, 99% of the time nothing is created and 1% of the time a red mushroom with no metadata is created. Interestingly, the command flag does seem to be executed sometimes, but the behaviour is unpredictable.
```
SMELT roastedRedMushroom
red_mushroom % 30
= 1% red_mushroom
  @name &dRoasted Red Mushroom
  @enchant unbreaking 1
  @lore &f&oRed mushrooms... or brown ones?
  @command msg {player} Mushrooms, mushrooms! 
```
For what it's worth, the bug occurs in all instances when the player does not drag the item into the top slot of the furnace--hoppers do not work, and copying a furnace which has had the item dragged in with WorldEdit also does not work.

**Comment by haveric** [comment]
I've made some major changes to furnaces in the last couple days, which should help with the issues here and a few others that I found while testing. Just need to do some more testing to make sure I didn't break anything else before a release.
