### ISSUE TITLE
@command sometimes triggering on recipe fail.

### ISSUE THREAD

**Issue by ahoyaharr** [haveric/RecipeManager2#48]
```
SMELT roastedRedMushroom
red_mushroom % 30
= 1% red_mushroom
  @name &dRoasted Red Mushroom
  @enchant unbreaking 1
  @lore &f&oRed mushrooms... or brown ones?
  @command msg {player} Mushrooms, mushrooms! 
```

Sometimes the @command flag is triggered even when the recipe fails. Behaviour is unpredictable, but it happens frequently enough that it is repeatable.

**Comment by haveric** [comment]
This is fixed in one of the latest commits. There should be a release soon, but I need some time to do more testing of furnace behavior.
