### ISSUE TITLE
spawn eggs are not recognized

### ISSUE THREAD

**Issue by Pilvinen** [haveric/RecipeManager2#55]
Due to Mojang changes spawn eggs now use NBT data to store their data instead of damage values - which were removed. So this does not work anymore:

```
smelt Kakku
monster_egg:90
= CAKE
@ingredientcondition spawn_egg | data 90 | name §fKakkutaikina

smelt Piirakka
monster_egg:61
= PUMPKIN_PIE
@ingredientcondition spawn_egg | data 61 | name §fPiirakkataikina
```

(I would get it working if I would recognize the item from name alone with ingredientcondition - but recipemanager won't let me add two "monster_egg" items without data, ie: "monster_egg:61" - which does not work anymore. If you try to add it with just sevenral "monster_egg" entries it will say he recipe has been added already and fails.)

**Comment by haveric** [comment]
This is waiting on Spigot to add the necessary API: https://hub.spigotmc.org/jira/browse/SPIGOT-1592

If you want to make this work with names for now, use a multi-result recipe:

```
smelt Kakku
monster_egg
= CAKE
@ingredientcondition spawn_egg | name §fKakkutaikina
= PUMPKIN_PIE
@ingredientcondition spawn_egg  | name §fPiirakkataikina
```
