### ISSUE TITLE
[Spigot 1.8.8] Can't use @itemname and @itemlore in brewing recipes

### ISSUE THREAD

**Issue by KsenMih** [haveric/RecipeManager2#62]
Hello,

I don't know if this is really a bug, but flags _@itemname_ and _@itemlore_ don't work with brewing recipes.

**Recipe :** 
http://pastebin.com/raw/UGagGM6W

**Recipe Result :** 
Stone (with no nbt tags)`

**Server Version :** 
CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**RecipeManager2 Version :** 
2.7.3 (Latest)

**Comment by haveric** [comment]
Are you placing the items in manually? What happens if you try it on a new brewing stand or replace the current brewing stand?  Does this still happen with only RecipeManager running?

**Comment by KsenMih** [comment]
The brewing stand and the water bottle/water are placed in manually. I've tried with all plugins disabled, except RecipeManager, and the result is the same. I will try more things Asap.

Thanks.

**Comment by haveric** [comment]
There's been a bunch of improvements to potions and brewing stands in v2.8, but I have not gone back and tested 1.8 versions of Minecraft. Please reopen or create a new ticket if this is still an issue with v2.8 of RecipeManager.
