### ISSUE TITLE
Recipe books show multiple ingredient quantities

### ISSUE THREAD

**Issue by MegaNarwhal** [haveric/RecipeManager2#64]
I have made some recipes and put them in a book, but sometimes when a book is spawned or when its contents are updated, this happens:
![2016-09-13_02 44 02](https://cloud.githubusercontent.com/assets/2307465/18463992/109e5192-795c-11e6-81ee-bdf22e253592.png)
The recipe should show an iron ingot, 2 gunpowder, and 3 gravel, but it displays duplicates of the ingredients that are used more than once in the recipe.

**Comment by haveric** [comment]
Can you provide the recipe that you used for this? You mention it sometimes happens, have you found any repeatable way to cause it to happen?

**Comment by MegaNarwhal** [comment]
This is the recipe:
```
combine Shotgun Shell
gravel + gravel + gravel + sulphur + iron_ingot + sulphur
= sulphur
@name §6Shotgun Shell
```
It seems to happen when a book is updated or when a book is spawned after running /rmreloadbooks or /rmreload.
