### ISSUE TITLE
Escalation of recipe bug.

### ISSUE THREAD

**Issue by ShadedJon** [haveric/RecipeManager2#65]
To reproduce, have two recipes in the config.

Start crafting recipe one, but shift click the result to cause it to deny the crafting.

Remove ingredients, make recipe two, click on the result as normal to craft it.

The resulting item is the result from recipe one.

I have a video and our config if you'd like more explanation. 

@haveric

**Comment by haveric** [comment]
Please provide the recipes you are using, the config, and video.

Also, what version of RecipeManager are you using and what version of Bukkit/Spigot are you running?

**Comment by ProgrammerDan** [comment]
(I'm co-admin with Shaded) 

Latest (2.8, revised & latest from BukkitDev) RecipeManager: (md5 : e2923dafaddeef0fa42c2b1d9240eda2 )

CraftBukkit version git-Spigot-72c2605-251a5b6 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

I'll leave it to Shaded to attach config & video.

**Comment by ShadedJon** [comment]
Here's the video:

https://www.youtube.com/watch?v=kwChY9WRKH4&feature=youtu.be

Here's the config:

http://pastebin.com/az2rWfnZ

**Comment by ShadedJon** [comment]
confirmed to have been fixed <3
