### ISSUE TITLE
@inventory anvil flag not working as expected

### ISSUE THREAD

**Issue by redmag3** [haveric/RecipeManager2#66]
I'm trying to apply the @inventory anvil / flag to a recipe, it restricts the recipe from being used in a crafting grid, but it does not give an output item when the ingredients are used in the anvil. I've been trying to find an example recipe to see if perhaps I'm not doing it right, but the example htmls don't have an example of that flag used.

**Comment by haveric** [comment]
That's not quite how the @inventory flag works. It can only be used in a crafting table/user crafting grid and this flag can restrict it to one of those (optionally with a name). Anvil recipes are not possible at this time.

**Comment by redmag3** [comment]
:C is there a potential eta for it being activated?

**Comment by haveric** [comment]
I looked into it about a week ago and it just doesn't work at this time. Not sure if some of it is handled client side or there just isn't support in Bukkit/Spigot. If I come across any updates, I'll revisit this.

**Comment by redmag3** [comment]
The one plugin I found that was able to modify anvils to accept emeralds for repair materials was this one at civcraft

https://github.com/Civcraft/WurstCivTools

Anything useful in there?
