### ISSUE TITLE
IngredientCondition for percentage results

### ISSUE THREAD

**Issue by UberPilot** [haveric/RecipeManager2#67]
Is there any way that there could be different sets of percentage results for different ingredient conditions? For example, if I wanted to make different types of bows with different types of strings with chances of failure based on the type string, how would I do that? If I'm not able to do that, is there any way that could be implemented?

**Comment by haveric** [comment]
This is unlikely to happen in the near future. Since it's been a couple years (sorry about that), if you have any updated ideas for this, please create a new ticket and we can discuss further.
