### ISSUE TITLE
Shulker box crafting removed (1.12)

### ISSUE THREAD

**Issue by YellowZaki** [haveric/RecipeManager2#69]
The plugin is working perfect on 1.12 (with the latest compiled source) but I have a strange problem: when I have these recipes:

----------------------------------------------------------------------------------

craft redsand
sand:0 + sand:0 + sand:0
sand:0 + dye:1 + sand:0
sand:0 + sand:0 + sand:0
= sand:1:8

craft redsandstone
sandstone:0 + sandstone:0 + sandstone:0
sandstone:0 + dye:1 + sandstone:0
sandstone:0 + sandstone:0 + sandstone:0
= red_sandstone:0:8

----------------------------------------------------------------------------------

Shulker boxes can't be dyed.

Thanks.

**Comment by haveric** [comment]
All special recipes are likely busted at the moment, hence why it hasn't been released. This has been an annoying update and I'm working to figure out a way to get back to stable.

**Comment by YellowZaki** [comment]
No, everything is perfect. That's the only bug I've found. And I have +50 special recipes on my server.

**Comment by ProgrammerDan** [comment]
So far that we've found, you won't have issues unless you remove / disable existing "vanilla" recipes. Then things get ... weird :D

**Comment by haveric** [comment]
@YellowZaki When I said special recipes, I'm referring to Minecraft's internal special recipes, such as map cloning and leather dying and a handful of others.

**Comment by haveric** [comment]
This has been fixed in the latest commits. Going to spend another couple days testing everything, but please feel free to compile it and let us know if there's any issues.

**Comment by YellowZaki** [comment]
I've compiled and it doesn't work neither. Leather armor, wool, shulkerboxes...

**Comment by ProgrammerDan** [comment]
Even on this latest release (merged last night?)

**Comment by YellowZaki** [comment]
Yes, I compiled 3 hours ago.

**Comment by ProgrammerDan** [comment]
Can you share with us all your custom recipes, so I can do my tests using your recipes?

Are you running any other plugins that might be working with recipes?

**Comment by YellowZaki** [comment]
Sure, I have been all the morning modifying stuffs but I could't get it to work:

https://jpst.it/10D1J

**Comment by ProgrammerDan** [comment]
Thanks, I'll give 'em a go

**Comment by ProgrammerDan** [comment]
So, shulker box dying, leather dying, all of it works just fine for me -- I'm running the config you gave, latest Spigot 1.12, and no other plugins.

I can't confirm the issue .. can you please let me know what other plugins you are running?

**Comment by YellowZaki** [comment]
I have tested again and now it works, really strange. I was like 2 hours this morning trying everything.
