### ISSUE TITLE
[Question] Disable diamond_hoe repaired through craft

### ISSUE THREAD

**Issue by YellowZaki** [haveric/RecipeManager2#71]
I'm doing this:

combine diamondhoe
@override
diamond_hoe:*:2
= grass

But it doesn't work, it gives 1 diamond hoe as recipe.

Thanks.

**Comment by haveric** [comment]
Repairing recipes is one of the many special recipes in Minecraft that acts as a multitude of recipes, but is actually only one recipe. You can disable repairing as a whole, not individual items.  If you wanted to disable all repairing. you can set special-recipes.repair to false in config.yml.
