### ISSUE TITLE
How to write # in item lore

### ISSUE THREAD

**Issue by YellowZaki** [haveric/RecipeManager2#72]
I'm writing this, but the # is not interpreted:

= diamond_chestplate
@itemlore <green>> Jetpack
@itemlore <gray>#Ultrasonico
@unbreakable

**Comment by haveric** [comment]
"#" by default is a comment character. You should be able to disable that by editing "recipe-comment-characters" in your config.yml

**Comment by YellowZaki** [comment]
Thanks.
