### ISSUE TITLE
rmcreaterecipe Crashes Server

### ISSUE THREAD

**Issue by MCTyler** [haveric/RecipeManager2#73]
name: RecipeManager
description: Add, edit or remove recipes and fuels
version: 2.11.0
authors: [haveric, Digi]
Here's a link to the rather lengthy error log....
https://pastebin.com/e98S5WCe

**Comment by haveric** [comment]
What items did you have in your left 9 slots and on the cursor?

**Comment by MCTyler** [comment]
I figured it out..it does that cause I didn't have them in the shape of the recipe. It should just output a error message though instead of crashing.

**Comment by haveric** [comment]
What do you mean by "I didn't have them in the shape of the recipe"?

**Comment by MCTyler** [comment]
I didn't understand exactly what you meant by the items "left" in your inventory so i had the items literally "left in my inventory...They were in my hotbar....Maybe I am just the one dunce :) who would do this lol.

**Comment by haveric** [comment]
Nope, I can understand how that can be confusing. Just to clarify, this only happens when all 9 left slots are empty, correct?

**Comment by MCTyler** [comment]
Thats the only time it happened to me, I didn't test it further.

**Comment by haveric** [comment]
Perfect, this will be fixed for the next version and I'll change the wording to hopefully make it less confusing.

**Comment by MCTyler** [comment]
When using /rmcreaterecipe Items must be in your internal inventory in the left 9 slots as they would be in a crafting table. The item you are creating will be in your hand.....
