### ISSUE TITLE
Need help with furnace recipes

### ISSUE THREAD

**Issue by SoSeDiK** [haveric/RecipeManager2#78]
I have some new fishes (~20+ pieces for now) and every fish is unique in its own way: name, lore, saturation points restore, potion effect on consume, texture (mcpatcher CIT feature) etc. Since fishes are initially raw and later you can cook them, I was wondering if I can add special furnace recipe to every fish. For example:
&3Fish1 > &dCooked Fish1
&3Fish2 > &dCooked Fish2
But @ingredientcondition can't be used in furnace recipes.
If there is any other decision it will be amazing! But fishes still must be food, so players can eat them with consume animation.
However if this can't be done, I will just add crafting recipe for workbench (fish + flint and steel, where flint and steel will lose some durability points at each crafting).

**Comment by haveric** [comment]
Although this is probably out of date, this is mostly a limitation with how furnaces work globally instead of per user and unlikely to be implemented anytime soon. If you have any ideas for how this could work in the future, please create a new ticket and we can discuss further.
