### ISSUE TITLE
Problem with a 'Shift' crafting

### ISSUE THREAD

**Issue by SoSeDiK** [haveric/RecipeManager2#82]
I have the recipe:
```
combine
@displayresult first
iron_nugget + iron_nugget + iron_nugget + shears
= 0% stick
@ingredientcondition iron_nugget | lore regex:&0sp:branch_[1-2]
@ingredientcondition shears | lore regex:&0sp:flint_knife
@lore &7Не самого лучшего качества,
@lore &7но и так сойдёт
= 60% stick
@ingredientcondition iron_nugget | lore regex:&0sp:branch_[1-2]
@ingredientcondition shears | lore regex:&0sp:flint_knife
@keepitem shears
= 29% stick:0:2
@ingredientcondition iron_nugget | lore regex:&0sp:branch_[1-2]
@ingredientcondition shears | lore regex:&0sp:flint_knife
@keepitem shears
= 3% stick:0:3
@ingredientcondition iron_nugget | lore regex:&0sp:branch_[1-2]
@ingredientcondition shears | lore regex:&0sp:flint_knife
@keepitem shears
= 8% fail
@ingredientcondition iron_nugget | lore regex:&0sp:branch_[1-2]
@ingredientcondition shears | lore regex:&0sp:flint_knife
@keepitem shears
```
When I use Shift for crafting it says that
`NOTE: Recipe has more than one result, shift+clicking will only craft it once.`
But it doesn't craft it and all items still present in crafting grid. However, there is an 8% chance to fail craft and in this case, items will decrease (just like without Shift). So when a player uses Shift with this recipe he can get only fail.

**Comment by haveric** [comment]
Sorry, for the late reply, but the just released v2.15.0 should have fixed this issue entirely with the new reworked shift click handling. If you're still having issues after updating, please create a new ticket and I'll be glad to help.
