### ISSUE TITLE
@noresult is ignored with shift-crafting

### ISSUE THREAD

**Issue by GiovanH** [haveric/RecipeManager2#83]
Recipe:
```
CRAFT Loot Crate
WOOD + WOOD + WOOD
WOOD + EMERALD + WOOD
WOOD + WOOD + WOOD
= CHEST
@ingredientcondition EMERALD | LORE Spin Token
@ingredientcondition EMERALD | amount 1
@sound UI_TOAST_CHALLENGE_COMPLETE
@inventory workbench
@noresult
@spawnparticle TOTEM | count 30 | randomoffset 0.5 0.5 0.5 | repeat 25 2
@spawnparticle CRIT | count 30 | delay 1 | randomoffset 0.5 0.5 0.5 | repeat 25 2
@command setblock {x} {y} {z} chest 1 0 {Lock:"Â§",LootTable:"gio:lootcrate"}
@itemlore Mystery Loot Crate 
@itemlore CAUTION: THIS WILL DESTROY YOUR WORKBENCH
```

Intended behavior: Clicking the output chest or shift-clicking the output chest turns the workbench into a chest with a specific loot table.

Actual behavior: Everything works as desired. However, if you shift-click the output chest in the crafting grid, you can get an actual copy of the item, even though the @noresult flag is present in the recipe. 

This server is running CraftBukkit version git-Spigot-596221b-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
RecipeManager version 2.14.1

**Comment by haveric** [comment]
Sorry for the late reply, but the newly released 2.15.0 should have fixed this issue. If you're still experiencing issues after updating, please create a new ticket and I'll be glad to help.
