### ISSUE TITLE
Gradle wrapper not commited

### ISSUE THREAD

**Issue by LonelyNeptune** [haveric/RecipeManager2#85]
Hi! I'm trying to use RecipeManager2 as a dependency in Maven with https://jitpack.io/

The build failed with the following log: https://jitpack.io/com/github/haveric/RecipeManager2/v2.14.1/build.log

Reading the log, I think the build is failing because the gradle wrapper can't been committed.

**Comment by haveric** [comment]
This should now be fixed using master-SNAPSHOT
