### ISSUE TITLE
error color potion flag

### ISSUE THREAD

**Issue by Diclo** [haveric/RecipeManager2#88]
the color flag does not work
[https://i.imgur.com/zfAXekC.png](url)
[https://i.imgur.com/vp92wjO.png](url)

**Comment by haveric** [comment]
It looks like you're trying to set the color on a custom effect, instead of the base potion. You'll want to add another `@potionitem` line above without the custom attribute in order to set the color.

**Comment by Diclo** [comment]
work xD

**Comment by Diclo** [comment]
Sorry, I don't know what's wrong here:
![imagen](https://user-images.githubusercontent.com/25293585/64069864-79695500-cc10-11e9-829c-e49178fabd9e.png)
the golden_pickaxe are not enchant and the recipes ignores it
![imagen](https://user-images.githubusercontent.com/25293585/64069867-85edad80-cc10-11e9-8833-e1737a05dea7.png)

**Comment by haveric** [comment]
`@ingredientcondition` is used globally in ingredients unless the needed flag is used. I'm guessing something is conflicting by duplicating the same condition. Try writing as follows:
`@ingredientcondition golden_pickaxe | enchant Efficiency 3 | data new | needed 1`
`@ingredientcondition golden_pickaxe | enchant DIG_SPEED 3 | data new | needed 2`

**Comment by Diclo** [comment]
no, same problem.
![imagen](https://user-images.githubusercontent.com/25293585/64080448-7ffbd900-ccb1-11e9-86a8-95edf943cd66.png)
![imagen](https://user-images.githubusercontent.com/25293585/64080452-8ab66e00-ccb1-11e9-9bb5-2028420e3ffa.png)

**Comment by haveric** [comment]
I think you might have misunderstood the needed condition. It isn't index based. Instead it says how many of the ingredients need to be matched instead of all of the ingredients. I only provided two lines because you need 1 Efficiency and 2 dig_speed matches. Your third line is saying that all 3 need to match dig_speed.

**Comment by Diclo** [comment]
@ingredientcondition golden_pickaxe | enchant DIG_SPEED 3 | data new | needed 3
@ingredientcondition golden_pickaxe | enchant DIG_SPEED 3 | data new 
@ingredientcondition golden_pickaxe | enchant DIG_SPEED 3 | data new
but same result

**Comment by haveric** [comment]
Please try ONLY the two lines provided in my previous comment.

**Comment by Diclo** [comment]
![imagen](https://user-images.githubusercontent.com/25293585/64096299-87a59700-cd1e-11e9-81b7-afb6952856cd.png)
sorry but not me work

**Comment by haveric** [comment]
Sorry, didn't realize Efficiency and dig_speed were actually the same, you'll only need one @ingredientcondition with a needed 3 at this point.

With that said, I am able to replicate this issue for the enchantments.

**Comment by Diclo** [comment]
![imagen](https://user-images.githubusercontent.com/25293585/64097240-f1bf3b80-cd20-11e9-8ef8-efe8eee8de92.png)
I try using efficiency and dig_speed and the same result, ignore the enchant in the recipe

**Comment by haveric** [comment]
Thanks for the report, this should get fixed in the next release.

**Comment by haveric** [comment]
This fix has been included in the v2.17.2 release. Please create a new ticket if any issues come up.
