### ISSUE TITLE
Disabling furnace recipe is not working.

### ISSUE THREAD

**Issue by Seanoo1** [haveric/RecipeManager2#93]
I removed furnace recipe, but its not working,

plugin version : v2.22.2

Server version : 1.8.8 tacospigot.

**Comment by haveric** [comment]
Can you share your recipe/recipe file? Do you have other recipes that work? Do you have any errors in the log or in the RecipeManager plugin folder?

**Comment by Seanoo1** [comment]
no errors, ok, I will share my recipe files,
https://drive.google.com/open?id=1kc8QfuAhcXQyBUQ-RSBsnU189G0_zOx0

**Comment by haveric** [comment]
Thanks, I'll dig into this when I get a chance. In the mean time, can you give me any more specifics to help narrow down the issue? Are all of the smelt recipes not working or just one? Are recipes before and after those working correctly?

**Comment by Seanoo1** [comment]
all of the smelt recipe not working, and I used recipe manager since v2.22.1 so I don't know when did smelt recipe is not working

**Comment by haveric** [comment]
Sorry, I meant the recipes above and below the ones that are not working. Are all of those working as intended?

**Comment by Seanoo1** [comment]
all of the recipes are working, except smelt recipes.

Sorry, I don't understand well what your saying...

**Comment by haveric** [comment]
Dev build with this fix can be found [here](https://cdn.discordapp.com/attachments/605797523935985686/719416629376843848/RecipeManager.jar) or referenced on the rm-devbuilds channel in [discord](https://discord.com/invite/3JY9JC3). Please let me know if you have a chance to test it and feel free to reopen if your issue is not resolved.

**Comment by Seanoo1** [comment]
ok I will test 9 hours later

**Comment by Seanoo1** [comment]
fixed. Thanks
